services:
    fq.joined_date_format.listener:
        class: fq\joindateformat\event\listener
        arguments:
            - @config
            - @user
        tags:
            - { name: event.listener }
