services:
    fq.joindateformat.listener:
        class: fq\joindateformat\event\listener
        arguments:
            - @config
            - @user
        tags:
            - { name: event.listener }
